## Tic tac toe for 2 players
* player 1: human  
* player 2: human

In [1]:
!python --version

Python 3.7.12

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [134]:
def reset_board_values():
  
  """
  Start a new game by restting the playing board.
  Create empty 3x3 data frame to represent the playing board of 9 squares that can be selected by players. Possible values of squares:
  1 = square selected by player 1
  2 = square selected by player 2
  0 = square not yet selected by any player

  At the start of the games all squares are 0
  """
  dict_of_lists_values = {"col1":[0,0,0],
                          "col2":[0,0,0],
                          "col3":[0,0,0]}

  board_values = pd.DataFrame(dict_of_lists_values)
  return board_values

In [125]:
"""
Define how player can make a move by selecting a position.
create another 3x3 data frame which holds the numerical position assignment of each of the 9 squares.
A player make a move in the game by inputing the number of a square which the player wants to chooce
"""

dict_of_lists_positions = {"col1":[1,4,7],
                           "col2":[2,5,8],
                           "col3":[3,6,9]}
board_square_numbers = pd.DataFrame(dict_of_lists_positions)
board_square_numbers

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [147]:
# Step 1

# Create a new board
board_values = reset_board_values()
board_values

   col1  col2  col3
0     0     0     0
1     0     0     0
2     0     0     0

In [169]:
# Step 2

# Make a turn
try:
  player_number = int(input('Select player number (1 or 2)'))
  print(player_number)
  square_number = int(input('Select square number (Available values between 1-9):'))
  print(square_number)
except ValueError:
  print("not a number")

Select player number (1 or 2)1
1
Select square number (Available values between 1-9):5
5

In [170]:
# Step 3

# Update the board with a value
#def update_board(square_number, player_number)

if square_number == 1 and board_values.iloc[0][0] == 0:
  board_values.iloc[0][0] = player_number
elif square_number == 2 and board_values.iloc[0][1] == 0:
  board_values.iloc[0][1] = player_number
elif square_number == 3 and board_values.iloc[0][2] == 0:
  board_values.iloc[0][2] = player_number
elif square_number == 4 and board_values.iloc[1][0] == 0:
  board_values.iloc[1][0] = player_number
elif square_number == 5 and board_values.iloc[1][1] == 0:
  board_values.iloc[1][1] = player_number
elif square_number == 6 and board_values.iloc[1][2] == 0:
  board_values.iloc[1][2] = player_number
elif square_number == 7 and board_values.iloc[2][0] == 0:
  board_values.iloc[2][0] = player_number
elif square_number == 8 and board_values.iloc[2][1] == 0:
  board_values.iloc[2][1] = player_number
elif square_number == 9 and board_values.iloc[2][2] == 0:
  board_values.iloc[2][2] = player_number

else:
  print('Wrong selection, board not updated')
  print(f'Square number: {square_number}')
  print(f'Player number: {player_number}')

In [171]:
# Step 4 

# Check board values
board_values

   col1  col2  col3
0     1     2     0
1     0     1     0
2     0     2     1

In [197]:
# Step 5 - JATKA TÄSTÄ

# Evaluate the board if there are any winners!

m = board_values.sum(1).eq(3) # sum and check rows
print(m)
# board_values.sum(0).eq(3) # sum and check cols

# print(f'col1 values only 1: {sum(board_values.iloc[0] == 1) == 3}')
# print(f'col2 values only 1: {sum(board_values.iloc[1] == 1) == 3}')
# print(f'col3 values only 1: {sum(board_values.iloc[2] == 1) == 3}')

0     True
1    False
2     True
dtype: bool

In [44]:
board_square_numbers

   col1  col2  col3
0     1     2     3
1     4     4     6
2     7     8     9

In [145]:
# Reset board values
board_values = reset_board_values()
board_values

   col1  col2  col3
0     0     0     0
1     0     0     0
2     0     0     0